### ISSUE TITLE
Align 'legacy' version with phpunit supported versions?

### ISSUE THREAD

**Issue by zbateson** [sanmai/phpunit-legacy-adapter#2]
phpunit 4.8.35 supports php as old as 5.3.3, could the legacy version be extended to that maybe?

In my case, I'm trying to align zbateson/mail-mime-parser with supported redhat releases, so I only really 'want' 5.4, but I guess others may have other needs.

Also I didn't notice anything specific in the code that's not 5.3-compatible, it looks to me like it's just the version constraint in composer.json.

**Comment by sanmai** [comment]
Let me see if I can do that.

**Comment by sanmai** [comment]
OK, should be in a tagged release. Please let me know if something is off.

**Comment by zbateson** [comment]
Works well, thank you!

**Comment by sanmai** [comment]
You should now be able to use `doSetUp()` and `doTearDown()` and so on in addition to previously used `legacySetUp()`. This is done to make code portable [with `SetUpTearDownTrait` from PHPUnit-Bridge](https://github.com/symfony/phpunit-bridge/blob/5.x/SetUpTearDownTrait.php), but more so because PHP-CS-Fixer will sort these methods the same way it sorts `setUp()` and `tearDown()`.
